### ISSUE TITLE
Clojure programm

### ISSUE THREAD

**Issue by Abi-shan** [Luffy7854/1st-Project#2]
- Operate (if) with conditions

- Implement definitions

- Keyword increment by definitions

**Comment by Luffy7854** [comment]
the probleme with the operate "if" is still not resolved, I'm still looking for a solution but im sur at 90% it's a syntax error

the implementation of definition and keyword is done. The probleme was the syntax, in fact in these two cases i forgotten to put some "{"

**Comment by Luffy7854** [comment]
the "if" probleme is done, the probleme was before all "if" i had put some "cond" so it's was not possible to work
